name: datascience-ecommerce
dependencies:
  - python=3.8
  - nb_conda
  - pip:
    - jupyter
    - numpy
    - pandas
    - sklearn
    - kneed
    - matplotlib
    - countries
    - wordcloud
    - nltk
    - geopandas
    - descartes
    - seaborn
    - yellowbrick